name: Build and Publish

on:
  workflow_dispatch:
    inputs:
      publish_pypi:
        description: 'Publish to PyPI (true) or build executables? (false)'
        required: true
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
  push:
    tags:
      - "v*.*"

jobs:
  publish:
    if: startsWith(github.ref_name, 'v') || (github.event_name == 'workflow_dispatch' && github.event.inputs.publish_pypi == 'true')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get the latest tag
        id: get_latest_tag
        run: echo "latest_tag=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install packaging dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade certifi
          python -m pip install --upgrade setuptools>=61.0.0 wheel twine build
          python -m pip install -r requirements.txt

      - name: Build package
        run: python -m build

      - name: Upload to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
